name: Multi-Platform Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'          # Reagiert auf Tags wie "1.2.3"
      - '[0-9]+.[0-9]+.[0-9]+.*'        # Reagiert auf Tags wie "1.2.3.branchname"
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest] # Verschiedene Betriebssysteme
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run make

      - name: Publish Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
